name: 🐞 Bug Report
description: Report an issue you've encountered
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        ### 📋 Checklist
        Thank you for taking your time to report this bug!
        
        Before reporting, please ensure the following:
        - There is no existing issue for the problem you're reporting
        - You are using the **latest** available version of MFFS.
  - type: dropdown
    id: version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you running? Please note that only the versions listed below are supported. If you're running an outdated version, update to receive support.
      options:
        - "26.1.x"
        - "1.21.1"
        - "1.20.1"
      default: 0
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: |
        How do you trigger this bug? Please walk us through it step by step.
        If applicable, add screenshots to help explain your problem.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: |
        If applicable (crash, error output in console), please provide your debug.log **and** crash report.
        To upload logs, use an external paste site, such as [Github Gist](https://gist.github.com/) (recommended), [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com).  
        *Please note that we currently don't accept file uploads.*
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here, such as your current environment or other mods that might be causing this bug."
